---
title: ""
toc: true 
link-external-newwindow: true
---

## University of Oregon (Instructor)
ANTH 220-Introduction to Nutritional Anthropology (Winter 2025) </br>
ANTH 165-Sexuality and Culture (Summer 2023) 

## University of Oregon (Graduate Teaching Fellow)
ANTH 114-Pirates and Piracy (Fall 2021) </br>
ANTH 331-Cultures India and South Asia (Winter 2022) </br>
ANTH 165-Sexuality and Culture (Spring
2022, Spring 2023, Fall 2024) </br>
ANTH 161-Introduction to Cultural Anthropology (Fall
2023) </br>
ANTH 220-Introduction to Nutritional Anthropology (Winter 2023) </br>
ANTH 110-Introduction to Traditional Ecological Knowledge (Fall 2023) </br>
ANTH 332-Human Attraction and Mating Strategies (Winter 2024) </br>
ANTH 114-Pirates and Piracy (Summer
2024) </br>
ANTH 165-Sexuality and Culture (Fall 2024) 

## Sehgal Foundation (Capacity Building Sessions)
Qualitative Tool Development (Summer 2018) </br>
Community-based Participatory Methodologies (Winter 2018) </br>
Using PRA (participatory rural appraisal) techniques in extension research and hands-on exercise (Summer 2019)

